import { z } from "zod";
import type { Creator } from "@prisma/client";

export const creatorSchema = z.object({
  profileImage: z.string().url().optional().or(z.literal("")),
  name: z.string().min(2, "Name is required"),
  instagramUsername: z.string().optional().or(z.literal("")),
  platform: z.enum(["INSTAGRAM", "YOUTUBE", "TIKTOK", "FACEBOOK", "TWITTER", "LINKEDIN", "OTHER"]),
  niche: z.enum([
    "FITNESS",
    "DOCTOR",
    "NUTRITIONIST",
    "ATHLETE",
    "LIFESTYLE",
    "BEAUTY",
    "COMEDY",
    "FINANCE",
    "TECHNOLOGY",
    "FOOD",
    "FASHION",
    "OTHER",
  ]),
  creatorType: z.enum(["SCIENCE", "PERFORMANCE", "LIFESTYLE", "COMMUNITY", "CELEBRITY"]).default("LIFESTYLE"),
  collaborationCategory: z.enum([
    "BARTER",
    "GIFT_BOX",
    "STORY",
    "REEL",
    "AFFILIATE",
    "AMBASSADOR",
    "SPONSORED",
  ]).default("BARTER"),

  location: z.string().optional().or(z.literal("")),
  language: z.string().optional().or(z.literal("")),
  gender: z.string().optional().or(z.literal("")),
  email: z.string().email("Enter a valid email").optional().or(z.literal("")),
  phone: z.string().optional().or(z.literal("")),
  website: z.string().url("Enter a valid URL").optional().or(z.literal("")),

  followers: z.coerce.number().min(0).default(0),
  avgReelViews: z.coerce.number().min(0).default(0),
  avgStoryViews: z.coerce.number().min(0).default(0),
  avgLikes: z.coerce.number().min(0).default(0),
  avgComments: z.coerce.number().min(0).default(0),
  engagementRate: z.coerce.number().min(0).max(100).default(0),
  audienceAgeRange: z.string().optional().or(z.literal("")),
  audienceGenderSplit: z.string().optional().or(z.literal("")),
  audienceCountry: z.string().optional().or(z.literal("")),
  audienceCity: z.string().optional().or(z.literal("")),

  storyPrice: z.coerce.number().min(0).optional(),
  reelPrice: z.coerce.number().min(0).optional(),
  postPrice: z.coerce.number().min(0).optional(),
  youtubePrice: z.coerce.number().min(0).optional(),
  packagePrice: z.coerce.number().min(0).optional(),
  monthlyRetainer: z.coerce.number().min(0).optional(),
  productInterested: z.string().optional().or(z.literal("")),
  couponCode: z.string().optional().or(z.literal("")),
  deliverablesCompleted: z.string().optional().or(z.literal("")),
  affiliateAvailable: z.boolean().default(false),
  barterAvailable: z.boolean().default(false),

  managerNotes: z.string().optional().or(z.literal("")),
  previousCollaborations: z.string().optional().or(z.literal("")),
  specialRequirements: z.string().optional().or(z.literal("")),
  contractAttached: z.boolean().default(false),
  mediaKitAttached: z.boolean().default(false),

  relationshipStage: z.enum([
    "PROSPECT",
    "SHORTLISTED",
    "CONTACTED",
    "WAITING_REPLY",
    "INTERESTED",
    "NEGOTIATION",
    "PRODUCT_SENT",
    "CAMPAIGN_LIVE",
    "COMPLETED",
    "AMBASSADOR",
    "INACTIVE",
  ]),
  status: z.enum(["ACTIVE", "PAUSED", "BLACKLISTED"]),
});

export type CreatorInput = z.infer<typeof creatorSchema>;
export type CreatorFormInput = z.input<typeof creatorSchema>;

export function creatorToFormValues(creator: Creator): CreatorInput {
  return {
    profileImage: creator.profileImage ?? "",
    name: creator.name,
    instagramUsername: creator.instagramUsername ?? "",
    platform: creator.platform,
    niche: creator.niche,
    creatorType: (creator as any).creatorType ?? "LIFESTYLE",
    collaborationCategory: (creator as any).collaborationCategory ?? "BARTER",
    location: creator.location ?? "",
    language: creator.language ?? "",
    gender: creator.gender ?? "",
    email: creator.email ?? "",
    phone: creator.phone ?? "",
    website: creator.website ?? "",
    followers: creator.followers,
    avgReelViews: creator.avgReelViews,
    avgStoryViews: creator.avgStoryViews,
    avgLikes: creator.avgLikes,
    avgComments: creator.avgComments,
    engagementRate: creator.engagementRate,
    audienceAgeRange: creator.audienceAgeRange ?? "",
    audienceGenderSplit: creator.audienceGenderSplit ?? "",
    audienceCountry: creator.audienceCountry ?? "",
    audienceCity: creator.audienceCity ?? "",
    storyPrice: creator.storyPrice ?? undefined,
    reelPrice: creator.reelPrice ?? undefined,
    postPrice: creator.postPrice ?? undefined,
    youtubePrice: creator.youtubePrice ?? undefined,
    packagePrice: creator.packagePrice ?? undefined,
    monthlyRetainer: (creator as any).monthlyRetainer ?? undefined,
    productInterested: (creator as any).productInterested ?? "",
    couponCode: (creator as any).couponCode ?? "",
    deliverablesCompleted: (creator as any).deliverablesCompleted ?? "",
    affiliateAvailable: creator.affiliateAvailable,
    barterAvailable: creator.barterAvailable,
    managerNotes: creator.managerNotes ?? "",
    previousCollaborations: creator.previousCollaborations ?? "",
    specialRequirements: creator.specialRequirements ?? "",
    contractAttached: creator.contractAttached,
    mediaKitAttached: creator.mediaKitAttached,
    relationshipStage: creator.relationshipStage as any,
    status: creator.status,
  };
}
